const Data = [
  {
    id: 1,
    category: "education",
    icon: "icon-graduation",
    year: "2021 - present",
    title: "Bachelor's Degree",
    subt: "(CSE)",
    desc: "VIT Bhopal University , Sehore , Madhya Pradesh (IN)",
  },
  {
    id: 2,
    category: "education",
    icon: "icon-graduation",
    year: "2016 - 2020",
    title: "High School Degree",
    subt: "(9th - 12th)",
    desc: "Macro Vision Academy, Burhanpur , Madhya Pradesh (IN)",
  },
  {
    id: 3,
    category: "education",
    icon: "icon-graduation",
    year: "2007 - 2015",
    title: "Academic Degree",
    subt: "(1st - 8th)",
    desc: "St. Aloysius Senior Secondary School , Jabalpur , Madhya Pradesh (IN)",
  },
  {
    id: 4,
    category: "experience",
    icon: "icon-briefcase",
    year: "2022-Present",
    title: "Back-End Development ",
    desc: "Currently I'm learning tech like : MongoDB, NodeJS, ExpressJs",
  },
  {
    id: 5,
    category: "experience",
    icon: "icon-briefcase",
    year: "2020-2023",
    title: "Front-End Developer",
    desc: "Completed Learning Stuff like HTML5 , CSS3 , JavaScript , ReactJs ",
  },
  {
    id: 6,
    category: "experience",
    icon: "icon-briefcase",
    year: "2021-2022",
    title: "UI / UX",
    desc: "Learned To make responsive Designs for both Mobile and Web Applications",
  },
];
export default Data;
